% clear;clc;close all;

function ROI_statistics(varargin)
% ROI_statistics Select a data set from ROI, then
% click one of the plot-type push buttons. Clicking the button
% plots the selected data in the axes


global pixel_width pixel_height text_Info axes_index statistics_f1 ROI_ALLvalue Select;
% ROI_value=evalin('base','ROI_value');
ROI_ALLvalue=varargin{1};
Select=varargin{4};
ROI_value=ROI_ALLvalue{Select};
ROI_ALLColor=varargin{2};
color=ROI_ALLColor{Select};
% ROI_value=load('ROI_value.mat');
% ROI_value=ROI_value.ROI_value;
% vol_ROI=35859.375;

sta_value=ROI_value(:,1);


if (ishandle(statistics_f1))
    delete(statistics_f1);
end




statistics_f1=figure('Name',['ROI statistics_' varargin{3}],'NumberTitle','off','position',[150   140   700   490],...
                     'Color',[0.925 0.914 0.847],'Resize','off','UserData',Select);
                 
               
% Construct the components.
global RadioButton_h;

panel_background = uipanel('Parent',gcf,'Position',[.0 .0 1 1],...
                        'BackgroundColor',[0.925 0.914 0.847],'FontSize',11);
axes_background=axes('Units','pixels','Position',[10   90   500   395],'Color',[0 0 0]);
set(axes_background,'Color','k','XTick',[],'YTick',[]);
axes_index=axes('Units','pixels','Position',[100   140   400   310],'Color',[0 0 0]);
% get(gcf,'currentaxes')
panel_ROI = uipanel('Parent',gcf,'Title','ROI Statistics Results','Position',[.74 .18 .25 .81],...
                        'BackgroundColor',[0.925 0.914 0.847],'FontSize',10,'FontWeight','bold','ForegroundColor',color);
                                        

text_Info = uicontrol('Parent',panel_ROI,'Style','text',...
                        'String','','Position',[5,5,160,370],...
                        'BackgroundColor',[0.925 0.914 0.847]);

                    
pushbutton_Export = uicontrol(gcf,'Style','pushbutton',...
                        'String','Export Summary as...','Position',[520,5,170,30],'CallBack',...
                        ['global Select;',...
                        'ROI_statistics_Export(Select);']);
                                        
                                      
panel_index = uipanel('Parent',gcf,'Title','','Position',[.01 .075 .98 .095],...
                        'BackgroundColor',[0.925 0.914 0.847],'ForegroundColor',...
                        'r','FontSize',11); 
   
                    
                    
                    
                    
RadioButton_h(1) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','T2','Position',[10,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CreateFcn','set(gcbo,''value'',1)','CallBack',...
                        ['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 

RadioButton_h(2) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','ADC','Position',[100,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 
RadioButton_h(3) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','Lambda 1','Position',[190,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']);
RadioButton_h(4) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','Lambda 2','Position',[280,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 
RadioButton_h(5) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','Lambda 3','Position',[370,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 
RadioButton_h(6) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','MD','Position',[460,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']);
RadioButton_h(7) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','FA','Position',[550,25,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 

RadioButton_h(8) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','FI','Position',[10,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 
RadioButton_h(9) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','RA','Position',[100,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']);
RadioButton_h(10) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','VR','Position',[190,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 
RadioButton_h(11) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','VF','Position',[280,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']);
RadioButton_h(12) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','CL','Position',[370,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']); 
RadioButton_h(13) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','CS','Position',[460,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']);
RadioButton_h(14) = uicontrol('Parent',panel_index,'Style','RadioButton',...
                        'String','CP','Position',[550,5,90,18],...
                        'FontAngle','Oblique','FontSize',9,'BackgroundColor',[0.925 0.914 0.847],...
                        'CallBack',['global RadioButton_h ROI_ALLvalue;',...
                        'set(gcbo,''value'',1);',...
                        'set(RadioButton_h(RadioButton_h~=gcbo),''value'',0);',...
                        'ROI_statistics_showprofile(ROI_ALLvalue);']);

                    
                    
%===========(第一次開啟初始化)===========%     
axes(axes_index);
max_value=max(sta_value);%max
min_value=min(sta_value);%minimum
ave_value=mean(sta_value);%average
std_value=std(sta_value,0,1);%std
area_ROI=size(sta_value,1)*pixel_height*pixel_width;%面積大小
x=min_value:(max_value-min_value)*0.015:max_value;
hist(sta_value,x);
xlim([min_value-max_value*0.012 max_value+max_value*0.01]);
title('T2','Color','w','FontWeight','bold','FontAngle','Oblique')
set(axes_index,'Color','k','XColor','w','YColor','w','FontWeight','bold','FontAngle','Oblique');
xlabel('Values');ylabel('Frequency');
h=findobj(axes_index,'Type','patch');
set(h,'FaceColor','k','EdgeColor',color)

INFO{1,1}='T2:';
INFO{2,1}=['Area(pixel): ' num2str(size(sta_value,1))];
INFO{3,1}=['Area(mm^2): ' num2str(area_ROI,'%.2f')];
INFO{4,1}=['Mean: ' num2str(ave_value,'%.6f')];
INFO{5,1}=['Max: ' num2str(max_value)];
INFO{6,1}=['Min: ' num2str(min_value)];
INFO{7,1}=['Std: ' num2str(std_value,'%.6f')];
set(text_Info,'string',INFO,'Max', length(INFO),'HorizontalAlignment','Left','FontSize',9);                                    

                   
% assignin('base','ROI_value',ROI_value);

ALLRadioButton_h=evalin('base','ALLRadioButton_h');
ALLRadioButton_h{Select}=RadioButton_h;
assignin('base','ALLRadioButton_h',ALLRadioButton_h);

